
steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/b-profiles-461910/3b-backend', '.']

  # Step 2: Push Docker image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.iob-profiles-461910/3b-backend']

  # Step 3: Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        'run', 'deploy', '3b',   # <--- new service name
        '--image', 'gcr.io/b-profiles-461910/3b-backend',
        '--region', 'asia-south1',
        '--platform', 'managed',
        '--allow-unauthenticated',
        '--port', '8080',
        '--timeout', '600s'
      ]
